//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public int uId { get; set; }
        public int postcode { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string cname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string panelcount { get; set; }
        public string color { get; set; }
        public string inverter { get; set; }
        public string paneltype { get; set; }
        public string warehouseid { get; set; }
        public Nullable<int> serviceno { get; set; }
        public bool hasservice { get; set; }
        public bool isprivate { get; set; }
        public byte[] serviceblog { get; set; }
    
        public virtual servicecontracts servicecontracts { get; set; }
    }
}
