//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Collections.Generic;
    
    public partial class inverterbase
    {
        public int uid { get; set; }
        public System.DateTime date { get; set; }
        public string serial_no { get; set; }
        public string manefacture { get; set; }
        public string cname { get; set; }
        public int supplier_id { get; set; }
        public string extended_warenty { get; set; }
    }
}
