//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesreports
    {
        public int UID { get; set; }
        public System.DateTime lastGenereated { get; set; }
        public string generatedBy { get; set; }
        public string machineName { get; set; }
    }
}
