//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class servicebaseEntities : DbContext
    {
        public servicebaseEntities()
            : base("name=servicebaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<paneltypes> paneltypes { get; set; }
        public DbSet<salesreps> salesreps { get; set; }
        public DbSet<customers> customers { get; set; }
        public DbSet<servicecontracts> servicecontracts { get; set; }
        public DbSet<servicetypes> servicetypes { get; set; }
    }
}
