//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicecontracts
    {
        public servicecontracts()
        {
            this.customers = new HashSet<customers>();
        }
    
        public int sid { get; set; }
        public Nullable<int> servicetype { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string soldby { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool activeServiceCase { get; set; }
        public bool invoicePaid { get; set; }
        public bool renewmailsendt { get; set; }
    
        public virtual ICollection<customers> customers { get; set; }
        public virtual servicetypes servicetypes { get; set; }
    }
}
