//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceOverblik
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicetypes
    {
        public servicetypes()
        {
            this.servicecontracts = new HashSet<servicecontracts>();
        }
    
        public int tid { get; set; }
        public string sname { get; set; }
        public Nullable<double> price { get; set; }
        public int period { get; set; }
        public Nullable<double> startupfee { get; set; }
        public string servicelogo { get; set; }
        public string details { get; set; }
    
        public virtual ICollection<servicecontracts> servicecontracts { get; set; }
    }
}
